name: green-ai
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - pytorch::pytorch=2.5.*
  - pytorch::torchvision=0.20.*
  - jpeg
  - libpng
  - diffusers>=0.33,<0.36
  - transformers>=4.50
  - accelerate
  - pillow
  - python-dotenv
  - huggingface_hub
  - sentencepiece
  - protobuf
  - psutil
  - pip
  - pip:
      - gguf>=0.10.0
      - pruna-engine